# Generated by Django 5.0.1 on 2026-06-05 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("action", models.CharField(max_length=200)),
                ("entity", models.CharField(blank=True, max_length=200)),
                ("entity_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "AuditLogs",
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="AuditLogs_action_60a5b8_idx",
                    ),
                    models.Index(
                        fields=["username"], name="AuditLogs_usernam_3facc8_idx"
                    ),
                ],
            },
        ),
    ]
