# Generated by Django 5.0.1 on 2026-06-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_add_addons"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookingaddon",
            index=models.Index(
                fields=["booking"], name="BookingAddo_booking_b6569f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingaddon",
            index=models.Index(fields=["addon"], name="BookingAddo_addon_i_07b2bb_idx"),
        ),
    ]
